### ISSUE TITLE
No support for directories starting with dash

### ISSUE THREAD

**Issue by fregante** [bntzio/wipe-modules#3]
<img width="870" alt="cd -t" src="https://cloud.githubusercontent.com/assets/1402241/25889676/3d910ffc-359d-11e7-8b63-78329aacef74.png">

Same issue as #1, but different cause.

wipe-modules 1.1.1
bash 3.2.57(1)-release (x86_64-apple-darwin15)
OS X 10.11.6
(also tried with fishell 2.5.0)

(I'm working on a fix)

**Comment by fregante** [comment]
The issue were two folders named `-test` and `-unlisted`. Fixed in b70b109c2f66d903596bef1381a48db237b92eb7 using this suggestion https://serverfault.com/a/462740/207547

**Comment by bntzio** [comment]
Awesome! @bfred-it 😄 thx
