### ISSUE TITLE
Display space saved

### ISSUE THREAD

**Issue by fregante** [bntzio/wipe-modules#5]
It will make the process last longer but it's nice to see what's being removed and its size.

**Comment by bntzio** [comment]
@bfred-it yeah that's an awesome idea! looking forward to it 👍

**Comment by bntzio** [comment]
[v.1.2.0](https://github.com/bntzio/wipe-modules/releases/tag/v1.2.0) ready! 👉 It now displays old vs new disk space (5229cf2)

Closing now 🙂

**Comment by fregante** [comment]
Excellent! Thank you :)

```
 Our agent is examining your files... Hold on a sec. 

 4 node_modules successfully removed! 

 Your initial directory size was 976M 
 Now it is 714M! 
```
