### ISSUE TITLE
Add depth control

### ISSUE THREAD

**Issue by fregante** [bntzio/wipe-modules#6]
To safely keep files off git, I often keep my projects as

```
.
├── gorv
│   ├── site
│   └── originals
├── slate
│   ├── site
│   └── originals
```

So running wipe-modules on `.` won't work.

Perhaps `getopts` can be implemented to safely get arguments and flags instead of using `$1`/`$2`/...

The `tree` command I used to generate that display above has the flag `-L`

```
usage: tree [-acdfghilnpqrstuvxACDFJQNSUX] ...
  ------- Listing options -------
  -L level      Descend only level directories deep.
```

**Comment by bntzio** [comment]
@bfred-it Mm... interesting, any ideas on how to implement it?

Talking about depth control, that also could help finding the exact old projects in the directory.

Currently, to determine how "old" a project is `wipe-modules` checks the last modification date (`mtime`) of each project directory, the thing is... That date value only changes when a root level file is modified, not subdirectories, and most of the time when working on a project modification in files inside folders occur.

So implementing depth control will also help to solve that, to find with better precision, and obviously, to better locate the structure to work on as you said.

**Comment by fregante** [comment]
I think it's _as easy as_ mapping a `--level` flag to `find . -maxdepth $level`. The `$d` in `wipe "$d"` will automatically be `gorv/site`, no longer `gorv`. Implementation details of how you figure out how old a project is is irrelevant to this specific feature, I believe.

**Comment by bntzio** [comment]
Yep right, and yeah that may be the way to go.

**Comment by wesbos** [comment]
Yeah I just found some node_modules from an old project that were never found because they were 3-4 levels deep

**Comment by bntzio** [comment]
![screen shot 2017-09-21 at 6 49 43 pm](https://user-images.githubusercontent.com/3136873/30723544-a9ab6178-9efd-11e7-9863-df011059ad0f.png)

A little update, today I was working on implementing depth control, so far it does the searching of the modules at the specified level, the only thing that's left to implement is to actually move to the directory and remove the `node_modules` folder.

Also, I added support for `getopts` as @bfred-it suggested.

**Comment by pix2D** [comment]
@bfred-it Any reason this was never published to NPM as a new version?

**Comment by bntzio** [comment]
@pix2D the functionality for depth control is not 100% complete yet, so far the program only shows you what can be removed but not an option to remove the found modules, I'll be working on this beginning January and then publish version 1.3.0, meanwhile, a pull req is appreciated 😄happy new year! 🎉

**Comment by fregante** [comment]
I ended up just always using this. If I need some project I'll reinstall it.

```sh
# This shows what it will delete
find . -name node_modules

# This will delete all the folders
find . -name node_modules -exec rm -r "{}" \;
```
