### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by spences10** [bntzio/wipe-modules#9]
Just installed and run it and get a `FIND: Parameter format not correct` error:

![image](https://cloud.githubusercontent.com/assets/234708/26145185/671732fc-3ae3-11e7-973b-ae4fd5ec39c1.png)

**Comment by bntzio** [comment]
@spences10 nope! only unix systems (linux/mac) but I'm planning on creating a windows version! 😄

**Comment by spences10** [comment]
@bntzio is the Windows Linux Bash Shell that's available in Windows 10 going to help with this?

**Comment by bntzio** [comment]
@spences10 i don't really know, i suppose it should work - [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) - but i'm not 100% sure, i'll check it some time since i don't own a windows machine.

**Comment by spences10** [comment]
@bntzio I'll be setting up a Windows machine in the next few days that I'm going use bash as the default option. I'll let you know how it goes 👍

**Comment by bntzio** [comment]
Awesome, let me know how it goes! 😄
